from: api-server-dev from gitHub v1.1.1
spring:
  datasource:
    url: jdbc:mysql://192.168.70.130:3306/coinkm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 552211
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 2  #初始化连接大小
      max-active: 50 #最大连接数
      min-idle: 5 #最小空闲连接数
      max-wait: 1000
      query-timeout: 1000  #查询超时时间
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      validation-query: select 1
      validation-query-timeout: 1
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 30001
      async-close-connection-enable: true
      aop-patterns: com.coinkm.userServer.* # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      fail-fast: true
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        slf4j:
          enabled: true
        config:
          enabled: true
        encoding:
          enabled: true
        wall:
          enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: 192.168.70.130
    port: 5672
    username: rabbitadmin
    password: rabbitpwd

feign:
 hystrix:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
